#ifndef __TodoMooMooMainFrame__
#define __TodoMooMooMainFrame__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "generated.h"

//// end generated include

/** Implementing MainFrame */
class TodoMooMooMainFrame : public MainFrame
{
	protected:

    void disconnect();

    // Handlers for MainFrame events.
		void OnCloseEvent( wxCloseEvent& event );
		void fileExitSelection( wxCommandEvent& event );
		void newTaskButtonClicked( wxCommandEvent& event );
		void newSubtaskButtonClicked( wxCommandEvent& event );
		void moveTaskButtonClicked( wxCommandEvent& event );
		void doneButtonClicked( wxCommandEvent& event );
		void startTimerButtonClicked( wxCommandEvent& event );
		void stopTimerButtonClicked( wxCommandEvent& event );
		void paymentDetailsButtonClicked( wxCommandEvent& event );
		void newNoteButtonClicked( wxCommandEvent& event );
		void hideDoneButtonClicked( wxCommandEvent& event );
		void flatViewButtonClicked( wxCommandEvent& event );
		void expandAllButtonClicked( wxCommandEvent& event );
		void collapseAllButtonClicked( wxCommandEvent& event );
		void minimalizeWindowButtonClicked( wxCommandEvent& event );
		void settingsButtonClicked( wxCommandEvent& event );
		void aboutButtonClicked( wxCommandEvent& event );
		void newCategoryButtonClicked( wxCommandEvent& event );
		void allCategoriesButtonClicked( wxCommandEvent& event );
		void dataViewColumnHeaderClick( wxDataViewEvent& event );
		void dataViewItemActivated( wxDataViewEvent& event );
		void dataViewItemCollapsed( wxDataViewEvent& event );
		void dataViewItemCollapsing( wxDataViewEvent& event );
		void dataViewItemContextMenu( wxDataViewEvent& event );
		void dataViewItemDrop( wxDataViewEvent& event );
		void dataViewItemExpanded( wxDataViewEvent& event );
		void dataViewItemExpanding( wxDataViewEvent& event );
		void dataViewSelectionChanged( wxDataViewEvent& event );
	public:
		/** Constructor */
		TodoMooMooMainFrame( wxWindow* parent );
		virtual ~TodoMooMooMainFrame();
	//// end generated class members

    void clean();

};

#endif // __TodoMooMooMainFrame__
